### ISSUE TITLE
2nd QA meeting with team 4 [11/12/2023]

### ISSUE THREAD

**Issue by thomas-planchard** [algosup/2023-2024-project-2-x86-retrogaming-team-3#106]
1. **Teleporter Glitch:**
 When using the teleporter located on the left side of the maze, Pac-Man exits the maze entirely, allowing the player to make the maze disappear.

2. **Pac-Man Speed Issue:**
Pac-Man exhibits excessive speed

3. **Lack of Key Buffer:**
No key buffer is implemented, resulting in difficulty changing Pac-Man's direction.

**Comment by Quentin-Clement** [comment]
Thanks for the feedback, the speed has already been fixed, and the key buffer is currently being implemented by the dev team. We are aware of the teleporter glitch but it's not a priority at the moment, we will fix that bug in the future.
