### ISSUE TITLE
Technical specification problem with scale [BR] [01/12/2023]

### ISSUE THREAD

**Issue by robin-debry** [algosup/2023-2024-project-2-x86-retrogaming-team-3#29]
### Description

We decided to resize all the games. In the technical specification, you need to change each size to the correct one.

### Severity

1 - Critical

### Testing environment

Operating system: MacOS

### Expected result

The sizes of the entire set and the positions are corresponding to the new selected sizes.

### Actual result

Currently, a tile was made in 8x8 for example.

### Potential solution

In the future, the new size of a tile will be 6x6 so you need to change each character and position following this new size.

**Comment by mathiskakal** [comment]
References that need fixing:

- [ ] L 219 Minimal Resolution
- [ ] L 319+, assets size since resize to 6x6
- [ ] L 441 on the grid system
- [ ] L 444 Maze Grid image
- [ ] L 466 Font has been downscaled
- [ ] L 476 Score has been moved to the Left

**Comment by mathiskakal** [comment]
elements have been appended to a job list for exporting the new assets
