### ISSUE TITLE
7. Move Down [TC] [01/12/2023]

### ISSUE THREAD

**Issue by robin-debry** [algosup/2023-2024-project-2-x86-retrogaming-team-3#32]
### Description

Pac-Man moves downwards when the user clicks the down arrow on the keyboard.

### Severity

1 - Critical

### Action to realise

1. Launch the game
2. Press the down arrow on the keyboard

### Expected result

Pac-Man moves downwards until a collision happens or another arrow is pressed by the user.

### Status

Pass

### Last test date

14/12/2023

**Comment by Quentin-Clement** [comment]
We've discovered that when a movement key is held down, Pac-Man's speed increases, so the test case status will remain "Failed" until the problem is resolved.
